/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
  Submit: "Submit",
  Close: "Close",
  Date: "Date",
  Campaign: "Campaign",
  View: "View",
  Actions: "Actions",
  Pricing: "Pricing",
  Reschedule: "Reschedule",
  CreatedOn: "Created On",
  ManageCampaigns: "Manage Campaigns",
  UpcomingCampaigns: "Upcoming Campaigns",
  LiveCampaigns: "Live Campaigns",
  PastCampaigns: "Past Campaigns",
  Ahead1: "",
  Ahead2: "days ahead",
  Ago1: "",
  Ago2: "days ago",
  Ended1: "Ended",
  Ended2: "days ago",
};