export default {
  Submit: "Submit",
  Close: "Close",
  Date: "Date",
  Campaign: "Campaign",
  View: "View",
  Actions: "Actions",
  Pricing: "Pricing",
  Reschedule: "Reschedule",
  CreatedOn: "Created On",
  ManageCampaigns: "Manage Campaigns",
  UpcomingCampaigns: "Upcoming Campaigns",
  LiveCampaigns: "Live Campaigns",
  PastCampaigns: "Past Campaigns",
};